version: "3.9"

services:

  api:
    build: .
    container_name: securevault-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
      - clamav
    env_file:
      - .env
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/securevault
      JWT_SECRET: ${JWT_SECRET:?Set JWT_SECRET in .env}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:?Set ENCRYPTION_KEY in .env}
      REDIS_HOST: redis
      CLAMAV_HOST: clamav
      CLAMAV_PORT: 3310
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:8
    container_name: securevault-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: securevault-redis
    ports:
      - "6379:6379"

  clamav:
    image: clamav/clamav:stable
    container_name: securevault-clamav
    restart: always
    ports:
      - "3310:3310"

volumes:
  mongo-data:
